version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: football-api
      MYSQL_USER: santex
      MYSQL_PASSWORD: santex
      MYSQL_ROOT_PASSWORD: therootpassword
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data_volume:/var/lib/mysql
volumes:
  data_volume: